// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYFjROdK7QgXZL2TPmpFRhvNyJI197RTk',
    appId: '1:699002286605:android:d2a585ee99dcc76759db44',
    messagingSenderId: '699002286605',
    projectId: 'selection-admin',
    storageBucket: 'selection-admin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgAzuMGyLMDVs-yc6Z6ATecOmx4_B9uNw',
    appId: '1:699002286605:ios:6384f268cd736f9059db44',
    messagingSenderId: '699002286605',
    projectId: 'selection-admin',
    storageBucket: 'selection-admin.firebasestorage.app',
    androidClientId: '699002286605-9ms8hsbev6mfbd5ss724rmai84bk4ikn.apps.googleusercontent.com',
    iosClientId: '699002286605-s0e1h3f305up89jadki6ae85bnle8o25.apps.googleusercontent.com',
    iosBundleId: 'com.menu2go.expressapp',
  );

}